login: &login
  adapter: postgresql
  username: crdata
  password: crdata123
  encoding: UTF8

development:
  database: crdata
  <<: *login  

test:
  database: crdata_test
  <<: *login
  
production:
  database: crdata_production
  <<: *login

cucumber:
  <<: *TEST